#!/usr/bin/env php
<?php
/*
 * JEXTER
 * Joomla console package builder
 * @author Konstantin Kutsevalov (AdamasAntares) <mail@art-prog.ru>
 * @version 1.0.0 alpha
 * @license GPL v3 (license.txt)
 *
 * Use:
 *   "$ ./jexter/create comp" - create component
 *   "$ ./jexter/create plg" - create plugun
 *   "$ ./jexter/create mod" - create module
 * also you can pass the name of new component as second argument
 *   "$ ./jexter/create comp poherator" - create component with name "comp_poherator"   ;)
 */

require 'lib/helper.php';
//require 'lib/JexterBuilder.php';
require 'lib/JexterCreator.php';

// check extensions
if (!extension_loaded('zip')) {
    out("The Zip php extension not installed!\n", 'red');
    exit;
} elseif (!function_exists('simplexml_load_file')) {
    out("The SimpleXml php extension not installed!\n", 'red');
    exit;
}

// parsing console arguments
$args = prepareArguments($argv, [
    '1' => ['name' => 'type', 'default' => 'mod'],
    '2' => ['name' => 'name', 'default' => ''],
    'myDir' => ['name' => 'myDir', 'default' => __DIR__],
]);

JexterCreator::run($args);

out("Finish\n", 'cyan');

